server:
  port: 8001
spring:
  jpa:
    hibernate:
      ddl-auto: validate

---

spring:
  profiles: default
  jpa:
    database: h2
  datasource:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
